name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Upgrade pip / tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Lint (ruff)
        run: |
          python -m pip install ruff
          ruff check .

      - name: Run tests (if any)
        run: |
          python -m pip install pytest
          pytest -q || echo "no tests or tests failed"
